name: Static code analysis
on:
  push:
    branches:
      - master
      - 1.2.0
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  check:
    name: Run static code analysis tools
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup python environment
        uses: actions/setup-python@v1

      - name: Install ansible packages
        run: pip install ansible ansible-lint ansible-review

      - name: Run linter on core and advanced-core roles
        run: ansible-lint -v roles/{core,advanced-core}/*

      - name: Run linter on example playbooks
        run: ansible-lint -v resources/examples/simple_cluster/playbooks/*.yml

      - name: Run ansible-review
        run: git ls-files | xargs ansible-review -d .ansible-review
